sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - rbx-2
env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite3
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2

before_script:
  - bin/calagator new spec/dummy --database=$DB --postgres-username=postgres
  - bundle exec rake app:sunspot:solr:start_with_waiting

script:
  - bundle exec rake spec --trace
cache: bundler

